Upgrade Instruction Page and New Blog Post
ZenUml/docs pull request #85
Opened 2024-02-29 06:43 UTC by iamshaynez

因为在本地做的时候顺序乱了，所以在一条 PR 包含了下面两部分：

**Instruction**

- https://content.docs-68d.pages.dev/upgrade
- https://content.docs-68d.pages.dev/confluence-migration-instructions/

**Blog Post**
- https://content.docs-68d.pages.dev/blog/2024/02/25/2024/sequence-diagram-for-every-architect

2024-03-03 06:15 UTC, MrCoder requested changes

2024-03-03 06:15 UTC, MrCoder commented on src/pages/confluence-migration-instructions.md
> +All the diagrams in your confluence pages created from ZenUML Confluence Lite Version, can not be processed by new installed Full version. The data can not be processed cross different plugins unless
语法错误：newly created.
> All the diagrams in your Confluence pages, created from ZenUML Confluence Lite Version, cannot be processed by the newly installed Full version.

2024-03-03 06:15 UTC, MrCoder commented on src/pages/confluence-migration-instructions.md
> +
添加一段让用户安心的话？
Your data will remain intact
All your diagrams, graphs, and API documents will persist throughout the migration. Even if you accidentally uninstall our application, your data will stay within your Confluence instance, allowing you to regain access simply by reinstalling our application.

2024-03-03 12:06 UTC, iamshaynez commented on src/pages/confluence-migration-instructions.md
> +All the diagrams in your confluence pages created from ZenUML Confluence Lite Version, can not be processed by new installed Full version. The data can not be processed cross different plugins unless
这里我的本意是新安装的 full version 无法直接操作 lite version create 的 data…

2024-03-03 12:07 UTC, iamshaynez commented on src/pages/confluence-migration-instructions.md
> +
好，明天加

2024-03-04 04:50 UTC, iamshaynez commented on src/pages/confluence-migration-instructions.md
> +All the diagrams in your confluence pages created from ZenUML Confluence Lite Version, can not be processed by new installed Full version. The data can not be processed cross different plugins unless
我整个大概重写了一下 wording，稍微应该歧义小一些……

2024-03-06 08:44 UTC, MrCoder approved these changes

2024-03-07 09:48 UTC, merged